//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterpretDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicFile
    {
        public int ID { get; set; }
        public int Title { get; set; }
        public int Interpret { get; set; }
    
        public virtual Interpret Interpret1 { get; set; }
        public virtual Title Title1 { get; set; }
    }
}
